"""add bug_reports table

Revision ID: ffc709c5d5bd
Revises: ca8c2e7b13e4
Create Date: 2026-06-21 13:03:56.965736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffc709c5d5bd'
down_revision: Union[str, None] = 'ca8c2e7b13e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bug_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=False),
    sa.Column('what_before', sa.Text(), nullable=False),
    sa.Column('what_after', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reporter_username', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bug_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bug_reports_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bug_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bug_reports_id'))

    op.drop_table('bug_reports')
    # ### end Alembic commands ###
