"""add experience_level to game_profiles

Revision ID: 4bf947005791
Revises: 86277245427b
Create Date: 2026-06-19 00:20:56.260163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bf947005791'
down_revision: Union[str, None] = '86277245427b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experience_level', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_profiles', schema=None) as batch_op:
        batch_op.drop_column('experience_level')

    # ### end Alembic commands ###
