"""initial schema

Revision ID: 86277245427b
Revises: 
Create Date: 2026-06-08 22:36:24.620968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86277245427b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('servers', sa.JSON(), nullable=False),
    sa.Column('game_modes', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_games_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('reputation_score', sa.Float(), nullable=False),
    sa.Column('reviews_received_count', sa.Integer(), nullable=False),
    sa.Column('reviewer_trust_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('game_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('main_role', sa.String(length=50), nullable=True),
    sa.Column('server', sa.String(length=20), nullable=False),
    sa.Column('rank', sa.String(length=50), nullable=True),
    sa.Column('in_game_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'game_id', name='uq_user_game')
    )
    with op.batch_alter_table('game_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_profiles_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_profiles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_profiles_user_id'), ['user_id'], unique=False)

    op.create_table('searches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('server', sa.String(length=20), nullable=False),
    sa.Column('roles_needed', sa.JSON(), nullable=False),
    sa.Column('max_players', sa.Integer(), nullable=False),
    sa.Column('min_rank', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('join_mode', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('searches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_searches_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_searches_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_searches_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_searches_server'), ['server'], unique=False)
        batch_op.create_index(batch_op.f('ix_searches_status'), ['status'], unique=False)

    op.create_table('participations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('creator_confirmed', sa.Boolean(), nullable=False),
    sa.Column('participant_confirmed', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['search_id'], ['searches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('search_id', 'user_id', name='uq_search_user')
    )
    with op.batch_alter_table('participations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_participations_search_id'), ['search_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_participations_user_id'), ['user_id'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_user_id', sa.Integer(), nullable=False),
    sa.Column('search_id', sa.Integer(), nullable=False),
    sa.Column('communication', sa.Integer(), nullable=False),
    sa.Column('attitude', sa.Integer(), nullable=False),
    sa.Column('skill', sa.Integer(), nullable=False),
    sa.Column('reliability', sa.Integer(), nullable=False),
    sa.Column('average_score', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('comment', sa.String(length=1000), nullable=False),
    sa.Column('would_play_again', sa.Boolean(), nullable=False),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['search_id'], ['searches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('author_id', 'reviewed_user_id', 'search_id', name='uq_review_unique')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_reviewed_user_id'), ['reviewed_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_search_id'), ['search_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_search_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_reviewed_user_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_author_id'))

    op.drop_table('reviews')
    with op.batch_alter_table('participations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participations_user_id'))
        batch_op.drop_index(batch_op.f('ix_participations_search_id'))
        batch_op.drop_index(batch_op.f('ix_participations_id'))

    op.drop_table('participations')
    with op.batch_alter_table('searches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_searches_status'))
        batch_op.drop_index(batch_op.f('ix_searches_server'))
        batch_op.drop_index(batch_op.f('ix_searches_id'))
        batch_op.drop_index(batch_op.f('ix_searches_game_id'))
        batch_op.drop_index(batch_op.f('ix_searches_creator_id'))

    op.drop_table('searches')
    with op.batch_alter_table('game_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_game_profiles_id'))
        batch_op.drop_index(batch_op.f('ix_game_profiles_game_id'))

    op.drop_table('game_profiles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_games_slug'))
        batch_op.drop_index(batch_op.f('ix_games_id'))

    op.drop_table('games')
    # ### end Alembic commands ###
